- LICENSE
> build: add license

- .github/workflows/flutter_test.yml
Havia faltado um "." na frente da pasta `github` com os workflows
> FEAT: adicionando flutter test ao CI/CD

- .gitignore
- app/lib/app/features/request_details/data/adapters/request_details_adapter.dart
- app/lib/app/features/request_details/data/adapters/status_details_adapter.dart
- app/lib/app/features/request_details/data/i_request_details_repository.dart
- app/lib/app/features/request_details/data/request_details_repository_impl.dart
- app/lib/app/features/request_details/entities/request_details_entity.dart
- app/lib/app/features/request_details/entities/status_details_entity.dart
- app/lib/app/features/request_details/interactor/request_details_controller.dart
- core_module/lib/core_module.dart
> fix: base_controller import on core_module and features request_details

- README.md
> Doc/Update README.md

- app/lib/app/(public)/welcome/welcome_page.dart
Foi criada a welcome page, dentro de (public)
> Feat: Cria Welcome Page

- app/lib/app/(public)/auth/register/non_editable_register_item.dart
- app/lib/app/(public)/auth/register/register_item_field.dart
- app/lib/app/(public)/auth/register/register_page.dart
- design_system/lib/src/buttons/coo_button/coo_button.dart
> Feat/#96-register-ui 

- app/lib/app/(public)/auth/login/login_page.dart
#72 
[Figma](https://www.figma.com/design/shzDehDlqvywbsQhaeowZ0/CooPartilhar?node-id=1217-7773&t=ntycpn95UiKK2A6A-0)
**Segue alguns print para ajudar no review:**
> feat: Implementar layout da tela de login

- app/lib/app/features/check_affiliated/data/adapters/check_affiliated_adapter.dart
- app/lib/app/features/check_affiliated/data/adapters/document_adapter.dart
- app/lib/app/features/check_affiliated/data/check_affiliated_repository_impl.dart
- app/lib/app/features/check_affiliated/entities/check_affiliated_entity.dart
> [FEAT #65]- Create check_affiliated data

- .gitignore
- README.md
- melos.yaml
- pubspec.yaml
> Melos adicionado ao projeto
Resolves #155
> feat: qualidade de vida

- app/lib/app/(public)/onboarding/onboarding_page.dart
- app/lib/app/(public)/splash/splash_page.dart
- app/lib/app/features/auth/data/adapters/user_adapter.dart
- app/lib/app/features/auth/interactor/controllers/login_controller_impl.dart
- app/lib/app/features/auth/interactor/states/auth_sate.dart
- app/lib/app/features/auth/interactor/states/auth_state.dart
- app/lib/app/features/onboarding/data/onboarding_repository_impl.dart
- core_module/pubspec.yaml
Resolves #159
- verifica se tem o usuario no cache;
- caso sim direciona para o welcome;
- caso não direciona para a verificação de cooperado;
- tela de onboarding removida do fluxo inicial e marcada como v2;
> fix: fluxo inicial #159

- app/android/app/src/debug/AndroidManifest.xml
- app/android/app/src/main/AndroidManifest.xml
- app/android/app/src/profile/AndroidManifest.xml
- app/android/settings.gradle
Feita a correção de versão do kotlin para poder rodar a dependencia do LOCATION criada no core_module.
> fix: Correção de versão do kotlin

- design_system/lib/design_system.dart
- design_system/lib/src/buttons/coo_button/coo_text_button.dart
Adicionado CooTextButton para usar na tela de Onboarding no botão "Já tenho cadastro"
> feat: design system - add text button (CooTextButton)

- app/lib/app/(public)/onboarding/onboarding_page.dart
- app/lib/app/(public)/splash/splash_page.dart
> Fix/#205 - Alteração de fluxo de tela (Splash e Onboarding)

- app/lib/app/features/auth/data/repositories/auth_repository_impl.dart
- core_module/lib/src/client/dio/dio_adapter.dart
- core_module/lib/src/client/rest_client_exception.dart
- core_module/lib/src/errors/base_exception.dart
> fix: handler error message in login

- app/lib/app/(public)/request_details/request_details_page.dart
- app/lib/app/(public)/request_details/widgets/request_details_card/request_details_card.dart
- app/lib/app/(public)/request_details/widgets/request_details_card/request_details_card_created_at_date.dart
- app/lib/app/(public)/request_details/widgets/request_details_card/request_details_card_description.dart
- app/lib/app/(public)/request_details/widgets/request_details_card/request_details_card_header.dart
- app/lib/app/(public)/request_details/widgets/request_details_card/request_details_card_situation.dart
- app/lib/app/(public)/request_details/widgets/request_details_card/request_details_card_user_details.dart
- app/lib/app/(public)/success_state/success_state_page.dart
- app/lib/app/features/check_affiliated/interactor/check_affiliated_controller.dart
- app/lib/app/features/request_details/data/adapters/request_adapter.dart
- app/lib/app/features/request_details/data/adapters/request_user_adapter.dart
- app/lib/app/features/request_details/data/repositories/request_details_repository_impl.dart
- app/lib/app/features/request_details/interactor/controllers/request_details_controller.dart
- app/lib/app/features/request_details/interactor/repositories/i_request_details_repository.dart
- app/lib/app/features/request_details/interactor/state/request_state.dart
- core_module/lib/src/adapters/date_adapter.dart
- core_module/lib/src/entities/request/god_father.dart
- core_module/lib/src/entities/request/request_entity.dart
- core_module/lib/src/entities/request/request_status_entity.dart
- design_system/lib/src/lotties/coo_lotties.dart
- design_system/lib/src/tags/tag.dart
> feat: add integration request details and godFather flow

- app/lib/app/(public)/auth/login/widgets/password_text_form_field.dart
resolves #249 
Segue a image, expectativa e como ficou:
> fix: obscure icon in login

- app/lib/app/(public)/auth/login/reset_password_page.dart
- app/lib/app/(public)/auth/login/widgets/password_text_form_field.dart
- app/lib/app/features/register/interactor/controllers/register_controller.dart
- app/lib/app/features/reset_password/interactor/controllers/reset_password_controller.dart
- core_module/lib/src/helpers/validators_helper.dart
- dashboard/lib/app/features/auth/interactor/value_objects/password_vo.dart
resolves #251 
Na esquerda como estava, na direita como ficou depois da correção.
> fix: validation messages in reset password

- app/lib/app/(public)/auth/login/login_page.dart
- app/lib/app/(public)/request_details/request_details_page.dart
- app/lib/app/(public)/request_details/widgets/request_details_card/request_details_card_description.dart
resolves #247 
images de como deveria ser e como está agora.
> fix: layout request details screen

- app/lib/app/(public)/auth/login/login_page.dart
> fix/#250 - fix forgotPasswordPage route

- app/dev.env
- dashboard/dev.env
A base URL foi atualizada para a seguinte link: https://theavddogmr766ol6bnz2xbune0jnngn.lambda-url.sa-east-1.on.aws/  
Fiz a alteração nos arquivos dev.env dos dois projetos (app e dashboard)
> fix: .env atualizado
